GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jhin",
    "password": "4444"
}

###
DELETE http://localhost:3001/api/users/6867873c0ad28df67ba98f51

