GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jhin",
    "password": "4444"
}

###
DELETE http://localhost:3001/api/users/687759c26976384998a66b71

